baseURL = "https://camel.apache.org/"
languageCode = "en-us"
title = "Apache Camel"
relativeURLs = true
disablePathToLower = true
staticDir = ["static", "documentation"]
disableKinds = ["taxonomyTerm"]
enableRobotsTXT = true
timeout = 300000

[blackfriday]
    nofollowLinks = true
    noreferrerLinks = true

[params]
    socialProfiles = ["https://twitter.com/ApacheCamel"]
    organizationLogo = "https://camel.apache.org/_/img/logo-d.svg"
    organizationDescription = "Apache Camel ™ is a versatile open-source integration framework based on known Enterprise Integration Patterns. Camel empowers you to define routing and mediation rules in a variety of domain-specific languages, including a Java-based Fluent API, Spring or Blueprint XML Configuration files, and a Scala DSL."

[caches]

    [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "12h"

    [caches.getcsv]
    dir = ":cacheDir/:project"
    maxAge = "12h"

[[menu.main]]
    name = "Blog"
    weight = 2
    identifier = "blog"
    url = "/blog/"
    pre = "./img/blog-icon.svg"

[[menu.main]]
    name = "Projects"
    weight = 3
    identifier = "projects"
    url = "/projects/"
    pre = "./img/project.svg"

[[menu.main]]
    name = "Documentation"
    identifier = "docs"
    weight = 4
    url = "/docs/"
    pre = "./img/docs-icon.svg"

[[menu.main]]
    name = "Community"
    identifier = "community"
    weight = 5
    pre = "./img/community-icon.svg"

[[menu.main]]
    name = "Download"
    weight = 6
    identifier = "download"
    url = "/download/"
    pre = "./img/download-icon.svg"

[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 7
    pre = "./img/about-icon.svg"


[module]

  [[module.mounts]]
    source = "documentation/_/data"
    target = "data"
